version: '3'

networks:
  front-end_server_default:
    external: false
services:
  taskle_front-end:
    container_name: taskle_react-app
    networks:
      - front-end_server_default
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      REACT_APP_API_URL: http://localhost:3333
    ports:
      - '3000:80'